### ISSUE TITLE
Application vs. Enrollment

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#485] opened 2017-10-19 19:35 UTC
As @chj124 has pointed out, users of the PSM are *applying* to enroll in Medicaid (or some other program, in the future).  So, it would be better to use the term "application" than "enrollment" for the form the provider is filling out.  To update this term everywhere would mean a big code change which we aren't in a position to make right now (I don't think).  I am going to try to keep this distinction in mind going forward, especially as the PSM begins to incorporate more of the management side tasks.  One of those will be enrolling providers in the program *after* their application has been reviewed.

**Comment by jvasile** [comment] 2017-10-23 17:42
@PaulMorris since you're on the UI side, you should be aware of this.

**Comment by PaulMorris** [comment] 2017-10-25 21:08
Got it, thanks @jvasile .

**Comment by PaulMorris** [comment] 2018-08-01 14:34
See also #399 (closed as a duplicate of this issue).

**Comment by kfogel** [comment] 2018-08-01 20:09
Note that fixing this implies also fixing at least the titles of all issues that currently refer to "enrollment" where they really mean "application".  I mean, the issues fixup doesn't need to block this, but it's a task that should be done when the code is changed.

**Comment by PaulMorris** [comment] 2018-08-01 20:25
In #399 which is an earlier duplicate of this issue, @Cecilia Donnelly wrote:

> I asked one state about this and they said they say "application for enrollment."

Also Claude Hebert Jr. (@chj124) [indicated when asked about this](https://github.com/SolutionGuidance/psm/pull/410#issuecomment-335786210) that it's an application until it is approved and the provider is then enrolled, and only then would you say there was an enrollment.

**Closed** 2018-10-31 19:30 UTC
Labels: Z-REQ-PSM-FR-7.14, Z-REQ-PSM-SQ-1.5, in progress, tech-debt, ux
