### ISSUE TITLE
Add writing PR descriptions to CONTRIBUTING.md

### ISSUE THREAD

**Issue by PaulMorris** [SolutionGuidance/psm#703] opened 2018-03-08 16:13 UTC
Currently our CONTRIBUTING document does not cover writing good PR descriptions, although there are expectations about it.  It would be good to document our practice on this.

**Comment by jasonaowen** [comment] 2018-03-13 18:41
I agree! I think that the best way to do so is with a template. There's an existing issue for that, so I'm going to close this one. Thanks!

**Comment by jasonaowen** [comment] 2018-03-13 18:41
Duplicate of #312

**Closed by jasonaowen** 2018-03-13 18:41 UTC
