### ISSUE TITLE
Notify submitter & drafter via contact email when enrollment status changes

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#341] opened 2017-08-07 19:53 UTC
We should send a provider an email notification when their enrollment status (pending, modified, approved, or rejected) changes.

(Once this is implemented, it should be documented in `psm-app/docs/userhelp/source/service-admin-help.rst` .)

**Comment by brainwane** [comment] 2017-09-12 15:06
If a service agent or service admin submitted the enrollment, we should notify them as well. (If a provider started a draft and then a service agent finished and submitted it, we should notify both of them. If three or more users were involved in modifying or submitting the enrollment, we should notify all of them.)

**Comment by brainwane** [comment] 2017-10-31 20:51
@cecilia-donnelly If I understand correctly this is not in our deliverables for the end of December 2017; if I'm wrong please add this to the milestone.

**Comment by kfogel** [comment] 2017-12-19 04:00
Note that this will need to include a mechanism for configuring the outbound SMTP gateway (e.g., a state would probably want the PSM to use whatever SMTP server the state's other email-emitting MMIS modules use).  If the PSM isn't going to set up full SPF/DKIM/DMARC itself -- which it probably can't -- then it at least needs to empower system administrators to tell it how to use whatever they've already got set up.  Sending email reliably in the age of spammers is no fun :-).

**Comment by jasonaowen** [comment] 2017-12-20 22:46
@kfogel working outgoing email is [already a requirement](https://github.com/SolutionGuidance/psm/blob/master/INSTALL.md#mail), and is configured through the application server -- which, happily, means we do not need any custom code at all!

**Comment by cecilia-donnelly** [comment] 2017-12-21 19:55
@jasonaowen awesome!  Thanks for letting us know.

**Comment by jasonaowen** [comment] 2018-01-10 19:38
The easiest, first step is to send out emails when an enrollment application is either **approved** or **rejected**. We will need email templates for each. See, for example, the [registration success email template](https://github.com/SolutionGuidance/psm/blob/52ebd2984c00c4f7a33e41414e24fd3e4b0965af/psm-app/services/src/main/resources/emails/registration_success.txt).

If the contact email address is present, we would send to that; if it is not (if "same as above" is checked), we would send to the email address entered under the "personal info" section of the enrollment. One thing that is not clear to me: would we want to send an email to both the contact email address and the personal info email address, if they differ? Would we want to send an email to the user's email address, if it differs from both?

I'd also like some clarity on the other two triggers, an enrollment state becoming "pending" and an enrollment being modified.

An enrollment enters the "pending" state when the user finishes the enrollment process; do we want an email for that (basically, acknowledging the enrollment was submitted)? If so, we'll also need a template for that.

Service agents are no longer able to edit pending enrollments; service admins are the only ones who can. When an admin modifies and resubmits an enrollment, should they be copied on all future emails (pending, approve/reject)? It seems likely to me that would result in a lot of noise for them, as they might be the one clicking approve/reject. If so, we only have their user account's email address; is that acceptable?

We do not yet have enrollment sharing (as [discussed in #10](https://github.com/SolutionGuidance/psm/issues/10#issuecomment-336550730)), but once we do coauthors will need to be informed, too, as @brainwane mentions. Again, the only information we will have there is the user's email.

**Comment by cecilia-donnelly** [comment] 2018-01-10 22:39
- I like the idea of sending an email to the user's email address, as opposed to the personal info or contact address.  Note that as part of #34 we might be sending them some kind of email where they'll need to click a link to create an account, so we'll know that email address is working (as opposed to the contact or personal info addresses, which we will know have the right form but won't have tested).
- Pending: yes, let's send an email acknowledging that the enrollment was submitted. 
- That question about service admins is a tough one.  Maybe we can offer them the option?  If they click "Edit," then "Save" or "Submit," they could get a popup asking whether they want to receive email updates about this application.  Extra points if we track how often they say yes or no, for future decisions like this one.

**Comment by jasonaowen** [comment] 2018-01-10 23:07
Ah, good catch that the the email submitted with the enrollment is not verified!

So, maybe it would make sense to send an email to both of those (personal info email address, and contact info email address) to confirm, just like we want to do with #34 for user email addresses.

Otherwise, it seems weird to collect these additional email addresses but not use them - as a user, I think I might be surprised and a little frustrated if I submitted an enrollment and all the emails around it went to me instead of the contact person I entered.

**Comment by brainwane** [comment] 2018-01-11 22:40
My take:

* Send email to the user account's email address and, if different, the personal info email address as well, upon acceptance/rejection of the enrollment.

* If the user submitted a contact info email address that is different from the personal info email address, then send notification to the contact info address instead of the personal email address upon acceptance/rejection of the enrollment.

**Comment by cecilia-donnelly** [comment] 2018-01-11 22:42
I talked to @chj124 earlier and he confirmed the following:
- Currently, applicants receive an acknowledgment that their application has been received and a notification at the end of the process: notifying that they were accepted or denied, with reason for denial if applicable
  - If they're accepted, they have to sign and return something saying that they agree to provide services and giving them information about where to find rates, where to submit claims
- We may need to contact a group or facility that the provider is affiliated with, to confirm that the affiliation is correct
- Admins should see information about sent communications in their dashboard.  This goes along with something we've had a little conversation about: new applications need to be assigned to an admin.  Currently the PSM shows all applications to each admin user, which isn't a useful case management workflow.  In the future, when processing a case: someone will be assigned to work the application as a "case manager" on the state side.  They'd see activity about their cases on their dashboard (e.g. notifications).

**Comment by chj124** [comment] 2018-01-12 15:33
Just to add....

When using workflows, or work assignments, one admin should be able to see all applications and who they are assigned to. Other admins should only be able to see the applications assigned to them.

There should be an option to assign a group of applications to an admin.

When the application is filed there should be a notification email for the provider, and the agent (if applicable), and for the facility if multiple providers practice there. 

The notices could be different. Notice to facility would be that provider X applied to provide services from their facility.

**Comment by jasonaowen** [comment] 2018-02-13 22:26
A few thoughts on implementation:

- We have code in [`RegistrationServiceBean`](https://github.com/SolutionGuidance/psm/blob/9f7173e9ca91e11bab494a31beea4b569c6b5424/psm-app/cms-business-process/src/main/java/gov/medicaid/services/impl/RegistrationServiceBean.java#L487-L516) that sends email notifications based on templates; I was imagining extracting that code to a more generic/reusable class and using it for this feature, as well.
- If we want all notifications to be recorded, we should fix the password reset / new account handling (see #34), as currently we should probably not record those notifications. I haven't thought very hard about the database setup for that, but it doesn't feel particularly risky to me.
- The status notifications would probably be sent in [`AcceptedHandler`](https://github.com/SolutionGuidance/psm/blob/9f7173e9ca91e11bab494a31beea4b569c6b5424/psm-app/cms-business-process/src/main/java/gov/medicaid/process/enrollment/AcceptedHandler.java#L100), [`RejectedHandler`](https://github.com/SolutionGuidance/psm/blob/9f7173e9ca91e11bab494a31beea4b569c6b5424/psm-app/cms-business-process/src/main/java/gov/medicaid/process/enrollment/RejectedHandler.java#L98), and `EnrollmentPageFlowController` (for submission and resubmission).
- The notification templates feel pretty bikeshed-esque, so it might be worthwhile to work on those first, or at least start a WIP PR with a first draft to start gathering that kind of feedback early rather than blocking an otherwise-complete PR on wordsmithing.

**Comment by dan9000** [comment] 2018-02-15 17:40
I think this is an accurate summarization of the requirements here:

 - Send email notifications for enrollment status changes (pending, modified, approved, rejected)
 - Send email notifications to providers
 - Send email notifications to facilities if they have multiple providers
 - Send email notifications to service admins and/or service agents if they request it when submitting/modifying an enrollment
 - Use different email templates for each type of recipient (provider, facility, service agent/admin) and type of status change (pending, modified, approved, rejected)
 - Send provider notifications to the contact email address or as a fallback the personal email
 - Send provider notifications to the account address
 - Document feature in psm-app/docs/userhelp/source/service-admin-help.rst

**Comment by cecilia-donnelly** [comment] 2018-02-15 20:31
@dan9000 Yes, thank you!  The only specific change I would make to these is around "facilities."  The PSM doesn't currently have any concept of a "facility."  Vermont does, which is where @chj124's comments are coming from.  I would instead think of it as an organizational provider, if an individual provider is linked to that group.

I notice you have notifications going to both the contact email/personal email and the account email -- I think @jasonaowen and I left a dangling item there.  

One more thing: we want to be able to audit sent messages, so there'll need to be some way for us to store (and eventually, though not in this issue, display) sent messages.

**Comment by dan9000** [comment] 2018-02-22 17:14
WIP PR (https://github.com/SolutionGuidance/psm/pull/678) has the initial notification service and templates in place but it's not being called from the accepted/rejected handlers and I'm not sure why. Also work still needs to be done to gather which emails the notification should be sent to. And the admin dashboard info about sent notifications and persistence of sent emails needs to be done.

**Comment by cecilia-donnelly** [comment] 2018-03-01 17:20
Still to do:

- [ ] Call notification service from accepted/rejected handlers (that is, on change of application status)
- [ ] Get the account email and the "contact" email (if different), and send the notification to both of those.

The admin dashboard info that @dan9000 mentioned is a next step, beyond the scope of this issue.  We do, however, need to: 

- [ ] Store sent messages for auditing

**Comment by slifty** [comment] 2018-03-05 02:24
@cecilia-donnelly I'll want to better understand how we want to store sent messages (this will be best discussed over the phone)

Other open question is the actual mechanism for communicating emails to the service.  I'll put some thought to this as well after we catch up, and share notes here.

**Comment by slifty** [comment] 2018-03-08 04:48
Wanted to post an update here -- I've merged in @dan9000's code, set up my environment to be able to test email sending, and got caught up with the changes and general shape of the code related to this ticket.

As @dan9000 mentioned, the notification integration with the RejectHandler and AcceptHandler is in place but for some reason isn't being called.  It is possible those handlers may not be getting invoked at all...  I need to dig a little more, but will avoid spinning wheels too much.

**Comment by slifty** [comment] 2018-03-12 04:27
I know @jasonaowen has worked on these files so once he is back I imagine things will be more clear.

Rejecting an application triggers the [reject method in EnrollmentCenter](https://github.com/SolutionGuidance/psm/blob/9f7173e9ca91e11bab494a31beea4b569c6b5424/psm-app/cms-web/src/main/java/gov/medicaid/controllers/admin/EnrollmentController.java#L619-L636)

Eventually that winds up at [BusinessProcessServiceBean:completereview()](https://github.com/SolutionGuidance/psm/blob/9f7173e9ca91e11bab494a31beea4b569c6b5424/psm-app/cms-business-process/src/main/java/gov/medicaid/services/impl/BusinessProcessServiceBean.java#L328-L375)

It doesn't appear that the AcceptedHandler or RejectedHandler get triggered.  Is it possible they aren't actually connected to the approval process?

**Comment by jasonaowen** [comment] 2018-03-13 18:56
For those following along at home, @slifty and I were able to pair on this yesterday and untangle things a bit!

The `AcceptedHandler` does trigger on a successful approval, but the enrollment application must first pass the screening rules (see also #572), and failures there are not well-presented to the user.

The `RejectedHandler` turns out not to be triggered when an admin rejects an enrollment application in the review UI, because instead of calling [`reject`](https://github.com/SolutionGuidance/psm/blob/9f7173e9ca91e11bab494a31beea4b569c6b5424/psm-app/cms-web/src/main/java/gov/medicaid/controllers/admin/EnrollmentController.java#L619-L636), it instead calls [`rejectTicket`](https://github.com/SolutionGuidance/psm/blob/2427e4e45ddf0eaf1f7e23b2c476a8047b8f809c/psm-app/cms-web/src/main/java/gov/medicaid/controllers/admin/EnrollmentController.java#L277), which bypasses the handler.

@slifty will...
1. reduce the scope of the first pull request to only send an email on approved enrollments (since that part is working as expected)
2. open an issue for `RejectedHandler` not getting invoked
3. fix that issue (either by verifying that the `RejectedHandler` code is not used and deleting it, or by changing the admin UI to use the jBPM workflow instead of bypassing it - and delete the unused `reject` or `rejectTicket` method + endpoint to avoid future confusion!)
4. based on how that issue is resolved, add email notifications for rejections

**Comment by cecilia-donnelly** [comment] 2018-04-09 18:45
This can be closed once #737 and #750 are merged.

**Comment by cecilia-donnelly** [comment] 2018-04-25 17:12
Closing now that the associated PRs are merged.  Note some related work is happening in #770 (and PR #771).

**Closed by cecilia-donnelly** 2018-04-25 17:12 UTC
Labels: Z-REQ-PSM-FR-8.1, Z-REQ-PSM-FR-8.2, backend, enhancement, review, task
