### ISSUE TITLE
Add creation of gradle.properties file to INSTALL.md

### ISSUE THREAD

**Issue by lorinpa** [SolutionGuidance/psm#880] opened 2018-06-18 18:20 UTC
Section: Build and deploy the application, Step 4 creates database schema and initial data. Step 4 is missing a dependency: creation of gradle.properties file. The gradle.properties file must contain the psm postgesql credentials and jdbc database path.

The recommended addition should be located just above:
~~~ 
> ./gradlew db:update
~~~
Recommended addition:

Create gradle.properties file:
$ cp {/path/to/psm}/psm-app/gradle.properties.template  gradle.properties

Update the gradle.properties file. Replace UNAME the psm database user name, PWORD with psm database user password.
~~~
systemProp.databaseUser=UNAME
systemProp.databasePassword=PWORD
systemProp.databasePath=jdbc:postgresql:psm
~~~

**Comment by jasonaowen** [comment] 2018-06-18 22:33
Thanks, @lorinpa ! We have an issue open for this, #824, and there's already some commits and PRs linked to that issue . You've added some very helpful and well-written information, which I really appreciate; I'm going to move it into the other issue and close this one. :heart:

**Comment by jasonaowen** [comment] 2018-06-18 22:34
Duplicate of #824

**Closed by jasonaowen** 2018-06-18 22:34 UTC
