### ISSUE TITLE
When service admin edits pending enrollment, PSM inappropriately checks provider statement date

### ISSUE THREAD

**Issue by brainwane** [SolutionGuidance/psm#301] opened 2017-07-26 21:52 UTC
To reproduce:

* Create and submit an enrollment so that it's in the Pending state. (To do this, you'll need to state the current date in the Provider Statement screen.)
* Wait till at least the next day.
* Log in as a service administrator.
* Navigate to [the pending enrollments view](http://localhost:8080/cms/provider/search/pending?statuses=Pending&showFilterPanel=true) and click the Edit link for the pending enrollment, e.g., `cms/provider/enrollment/reopen?id=33` .
* Click on the Provider Statement tab, e.g., `javascript:submitFormById('enrollmentForm',%20'/cms/provider/enrollment/jump?page=Provider+Statement')`.
* Click on any other tab, such as License Info.

What should happen:

The PSM should allow you to go to that other tab to view the enrollment details.

What happens instead:

Although the URL changes (to, for instance, `cms/provider/enrollment/jump?page=License+Information`), the screen doesn't change away from the Provider Statement tab. An error message displays:

> Please correct the following errors:
> Provider statement signature date cannot be a past date.

This is inappropriate; we shouldn't be asking the service administrator to change the date that the provider attested to the accuracy of their submission.

**Comment by jasonaowen** [comment] 2018-08-13 19:37
We have additional direction around the date field, documented in issue #1021, which supersedes this issue. Closing as duplicate.

**Comment by jasonaowen** [comment] 2018-08-13 19:38
Duplicate of #1021

**Closed by jasonaowen** 2018-08-13 19:38 UTC
Labels: Z-REQ-PSM-FR-7.14, backend, bug, ux
