### ISSUE TITLE
Redesign Enrollment Review page

### ISSUE THREAD

**Issue by jasonaowen** [SolutionGuidance/psm#354] opened 2017-08-09 20:14 UTC
There is a lot of information an admin needs to see on the review page, and we should consider redesigning it to better present that information. Here's an example of the current page:

![screenshot 2017-08-08 14 34 56](https://user-images.githubusercontent.com/1494855/29141071-b7296bc4-7d1a-11e7-8502-043092b73ad1.png)

For each of the automatic screenings against external sources, there are several things we should be clearly communicating, which I think we are not now:
- Was the automatic screening successful, or was there an error?
- If the automatic screening was successful, was it positive or negative?
- Does the admin need to take any action? For example, if a match was found in the LEIE, does the admin need to manually verify the provider's SSN using the official LEIE site? Contrarily, if the NPI is not in the National Plan and Provider Enumeration System (NPPES), I don't think there is anything the admin needs to or can do - the enrollment should be rejected.
- If the admin needs to take an action, have they yet?

Right now, we're trying to fit most of that information into a two-state checkbox and a link, which is not great.

**Comment by cecilia-donnelly** [comment] 2017-08-14 18:33
@jvasile, @jasonaowen and I talked about the problem of showing three states in a two-state checkbox in IRC (transcript edited and condensed for clarity):

>vasile: Maybe instead of checkboxes, we need Check, X, Empty
vasile: Or Check mark, X, Question mark
cdonnelly: I like question mark!
cdonnelly: That gets to what the problem is right away.
vasile: The X should be red, the check should be green
vasile: It should pre-populate and then clicking should rotate
cdonnelly: clicking is very nice.  and I like that we wouldn't see the other options if the auto checks work 
>vasile: http://jsfiddle.net/9R2J7/1/
[...]
vasile: Ah.  The serious suggestion was an icon with three states.  clicking the icon takes us to the next state.
vasile: Back it with a form element to save state.

So:

Screening performed and provider not excluded: green checkbox
Screening not performed / errored: black question mark
Screening performed and provider excluded: red X

**Comment by jasonaowen** [comment] 2017-08-14 19:56
@cecilia-donnelly and I talked some more in IRC about this.

There are a few different workflows that we want to be able to accommodate for each of the external data sources:
- auto screening pass -> admin views results -> approves
- auto screening fail -> admin views results -> rejects
- auto screening fail -> admin views results -> admin does manual search (ie, verify SSN in LEIE) -> overrides and approves
- auto screening -> admin does additional, manual search -> approves or rejects

Those are probably both in order of both priority and likelihood.

Something I think is both important and easy to convey is the distinction between the automatic screening results and the admin's response. #366 goes a little ways towards that, but we should also show the results of a successful automatic screening. I think the iconography @cecilia-donnelly  above would be useful here: green check for a successful, passed screening; red X for a successful, failed screening; question mark / error icon for an unsuccessful screening (not run due to some kind of error). Those can live beside or as part of the link to the automatic screening results, and (at least for now) we can leave the "Verified" checkbox as-is.

For auditability, we will probably want, at some point, to allow (or require) the admin to include an explanation of an override (in either direction?).

**Comment by cecilia-donnelly** [comment] 2018-03-29 16:21
#355 is probably a better explanation of what we need to handle in the [June](https://github.com/SolutionGuidance/psm/milestone/16) milestone, but I thought I'd include this just in case.

**Comment by frankduncan** [comment] 2018-06-25 17:39
This has been fixed in #813 and the open items are handled by the eventual work that will be done via issues like #875 where there is workflow enhancements.

**Closed by frankduncan** 2018-06-25 17:39 UTC
Labels: Z-REQ-PSM-FR-7.14, enhancement, ux
