### ISSUE TITLE
Remove date field from provider disclosure forms

### ISSUE THREAD

**Issue by jasonaowen** [SolutionGuidance/psm#1021] opened 2018-08-13 19:37 UTC
The final page of the enrollment application process involves a digital signature by the provider. Previously, this included a form element that required the user to enter the current date.

@jvasile [says](https://chat.opentechstrategies.com/#narrow/stream/6-Provider-Screening/subject/demos/near/51766):

> We should never ask the user to enter a date if there is only one possible right answer for that date.

(He also says not to worry about any supposed legal requirements around it; we'll establish what the legal reqs actually are and meet them, but meanwhile we shouldn't be implementing UX anti-patterns based on probabilistic impressions of legal requirements.)

Remove the date field from the provider disclosure forms, so as to improve the user experience, avoid unnecessary pseudo-legalisms, and improve the demo workflow.

(This also obviates #301, which I will close as a duplicate of this.)

**Comment by PaulMorris** [comment] 2018-08-13 20:16
I'm closing #162 as a duplicate of this issue, along with #301.  This issue (#1021) will cover both the provider and admin aspects of this (previously captured in #162 and #301), since they should be handled together rather than separately.

**Closed** 2018-08-22 18:49 UTC
Labels: Z-REQ-PSM-FR-7.14, backend, bug, enhancement, quick-fix, review, ux
