### ISSUE TITLE
Demo site should show date last updated, and Git commit ID of code it's running.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm#912] opened 2018-06-28 18:09 UTC
The login page of the demo site should show the date the site was updated, and the Git commit ID of the commit (presumably on `master`) that the site is running.  This can go right above or below the "This module is open source. Contributions welcome." message at the bottom of the login page.

It doesn't have to be called "Git commit ID" -- that won't be meaningful to most users -- but instead could be called "Development version alpha-8cd591232fa" or something, where "8cd591232fa" is a length of git commit ID prefix.

So, something like this:

> Provider Screening Module Demo Site: updated **28 June 2018** (development version alpha-8cd591232fa).  See [ProjectPSM.org](http://projectpsm.org/) for more information.

(Obviously there will need to be a configuration flag that says whether or not a site is a demo site, so that this doesn't get displayed on production sites.)

**Comment by jasonaowen** [comment] 2018-06-28 18:13
Duplicate of #250

**Closed** 2018-06-28 18:13 UTC

**Comment by jasonaowen** [comment] 2018-06-28 18:14
Good thought, @kfogel ! Issue #250 is very similar; would you like to add to it and/or rename it?
