### ISSUE TITLE
Tell developers how to automatedly create enrollments with sample data

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#280] opened 2017-07-19 19:13 UTC
When we're reviewing PRs (or demoing the system), it would be useful to be able to create sample enrollments without going through the entire workflow in the interface.  

See the [dev-sample-enrollment](https://github.com/OpenTechStrategies/psm/tree/dev-sample-enrollment) branch for my work on this so far.  @jasonaowen and I also talked about it in channel:

>cdonnelly: I'm working on the sample enrollment: https://github.com/OpenTechStrategies/psm/commit/6588afcc9e03f4a1c074f469111ff6026ebe7dcc
[...]
>jasonaowen: I think you have the right approach - create an enrollment or two, then dump the database and pick out the relevant bits
>jasonaowen: ooh, this might be easier: dump before and after, and diff
>cdonnelly: ohhh that's a great idea!
>cdonnelly: I was wondering if i'd actually included *too* much info
>jasonaowen: yeah, the comments and `SET` statements and so on shouldn't be needed
>jasonaowen: ideally just a few insert statements
>cdonnelly: so a diff is a great idea

**Comment by jasonaowen** [comment] 2017-07-25 16:41
We talked a bit about this in IRC. We came up with two approaches:

1. Manually drive the UI to create the sample data, and then create a SQL file with the newly-created data.
2. Write Serenity/Selenium tests to drive the UI to create sample data.

Using UI tests avoids the risk of primary key collisions, and avoids adding an additional thing to be maintained if and when we update the schema, but it also requires additional set up to use. After discussing the pros and cons, we decided to take the SQL approach, and document the steps to reproduce the data in a README file or similar.

**Comment by jasonaowen** [comment] 2017-07-25 16:43
The first piece of sample data we talked about is a **pending enrollment**: log in as a provider, create an enrollment, and submit it. This makes it easier to test the admin review process.

Another piece of sample data I would like is a **ready-to-submit draft enrollment**. This will make it easier to test the jBPM workflow that happens at submission.

**Comment by BenGalewsky** [comment] 2017-08-02 20:21
I took a crack at this. The results are in the branch `280_create_enrollments_with_sample_data`

There are some issues with this approach

1. A pure diff won't work since there is no guarantee of the order that 
the statements are generated. It's very easy for diff to get confused and 
output some lines that are in the original db_dump, but just far enough away 
from where they appear in the new file that they are flagged as only in the 
new file. Sorting the files won't work since there are foreign key 
relationships that wind up in the wrong order.

I generated the initial file with the command:

`pg_dump -U psm -d psm --column-inserts  | sed -e '/^--/d' > psm-app/db/empty.sq`

I generated the second file (after creating an enrollment as)

`pg_dump -U psm -d psm --column-inserts  | sed -e '/^--/d' > psm-app/db/enrollment.sql`

Then tried to get a useful diff with 

`comm -13 empty.sql enrollment.sql > psm-app/db/insert_test_enrollment.sql`

It generated a number of errors when I tried to load it.


2. I looked at the diff and saw that the only tables that seem to change are:

```
addresses 
affiliations
contacts 
content 
enrollments 
entities 
eventtypes  
organizations
people
processinstanceinfo 
sessioninfo
task
workiteminfo
```

I tried a pg_dump that just grabs those tables:
`pg_dump -U psm -d psm -c --column-inserts -t addresses -t affiliations \
-t contacts -t content -t enrollments -t entities -t eventtypes \
-t organizations -t people -t processinstanceinfo -t sessioninfo -t task \
-t workiteminfo > psm-app/db/insert_test_enrollment.sql`

I included `-c` option to make sure that existing tables and their constraints 
are deleted. Otherwise you wind up with a lot of duplicate constraint and 
primary key exceptions.


After trying that, I relaunched the app and it comes up with no errors, but 
you can't see any enrollments in the dashboard.

**Comment by brainwane** [comment] 2017-10-31 21:28
@jasonaowen If I recall correctly there's a chunk of code somewhere among your local branches to help do this?

**Comment by jasonaowen** [comment] 2017-10-31 21:48
@brainwane I'm afraid there is not! Also, since we had that discussion, we *have* created a Serenity test to create a new enrollment, in #429. So, I vote to close this.

**Comment by brainwane** [comment] 2017-10-31 21:52
OK, I've decided this issue is now: add some text to `TESTING.md` explaining to developers how to run individual Serenity tests, such as enrollment submission, so I can run that one test on my machine as a prerequisite to manual testing I want to do or a demo I want to run.

**Closed** 2018-01-30 22:27 UTC
Labels: docs, infra
