### ISSUE TITLE
Drifting dropdown in admin dashboard

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm#804] opened 2018-05-03 21:04 UTC
On the "Pending" tab of the "Enrollments" page, when logged in as a service admin, the dropdown governing how many results to show has moved behind the NPI/UMPI label:

![screenshot-2018-5-3 enrollment](https://user-images.githubusercontent.com/1497818/39602703-95a2f2ec-4eeb-11e8-96e3-a32eba7385c8.png)

I've only seen this in Firefox.

**Comment by PaulMorris** [comment] 2018-08-16 15:59
Closing this issue because the problem is no longer occurring.  We have now removed the (redundant and distracting) "Pending Enrollments" from the "Displaying 1 - 10 of 60 Pending Enrollments" which leaves enough room for the drop down menu.

![screenshot_2018-08-16 pending enrollments](https://user-images.githubusercontent.com/1091693/44220104-ace35980-a14b-11e8-9155-540479283b17.png)

**Closed by PaulMorris** 2018-08-16 15:59 UTC
Labels: Z-REQ-PSM-FR-7.14, bug, ux
